### ISSUE TITLE
Analyze the result delta file. 

### ISSUE THREAD

**Issue by nevercast** [snej/zdelta#2]
Hello,

I would like to analyze the resulting delta file so that I can understand where the differences are (addresses in files) and the chunks of changes that are in the tree.

Can you provide information about understanding the zdelta file format? Currently I am only using zdc and zdu.

**Comment by snej** [comment]
The data format isn't anything you'd want to read -- it's impenetrable binary, and it won't tell you much about any high level changes. It's basically the same format as gzip: a list of byte-range substitutions, compressed with Huffman encoding. There are some RFCs describing it if you're curious, but it's one of the most complex formats I know of.

If your data is textual, a regular diff algorithm would be the best choice. I don't know of any binary delta/diff programs that can display human-understandable results, sorry.
